### ISSUE TITLE
[Suggestion] Allow React to send commands

### ISSUE THREAD

**Issue by jonqrandom** [coolsquid/React#1]
please will you add a "command" action to React that executes a command as console? this would make it a _massively_ more powerful tool, as you'd be able to trigger e.g. .mcfunction files without having to have a main loop constantly running and testing various values!

the ability to substitute %target_type% with an appropriate value* would be awesome, but in all honesty i'd be very happy to even have the option to have React send commands at all. 

*(i.e. to substitute the appropriate UUID for the target %player% , %mob% , %sender% , %attacker% or %tamer%, the %dimension% number, or the x y z for the target %block%)

**Comment by coolsquid** [comment]
A "command" action will be added in the next release.

	player_log_in=[
		{
			action=server_command
			parameters {
				command="tell %%%player.uuid%%% Hello!"
			}
			conditions {
				side=server
			}
		}
	]
>the ability to substitute %target_type% with an appropriate value* would be awesome, but in all honesty i'd be very happy to even have the option to have React send commands at all.
>*(i.e. to substitute the appropriate UUID for the target %player% , %mob% , %sender% , %attacker% or %tamer%, the %dimension% number, or the x y z for the target %block%)

Instead of simply using %player%, %mob%, and so on, I've added a number of "properties" for each target type. Properties are used in combination with a target, e.g. "%%%mob.name%%%" or "%%%player.uuid%%%".
For example, this:

	player_sleep=[
		{
			action=log
			parameters {
				log_name=sleep # Newly added parameter, the log will be saved to logs/react/sleep.log
				message="%%%player.name%%% (id: %%%player.uuid%%%, position: %%%player.position%%%) has gone to bed."
			}
			conditions {
				side=server
			}
		}
	]
Produces this:

	[26.11.2017-13:57:14] [INFO]: Player735 (id: fd6f2cd7-e2c4-325a-9688-114cce28bfc9, position: [x=-31.301430173440238,y=64.0,z=95.4435380922974]) has gone to bed.`

As an additional enhancement for servers, the log action has been expanded to support custom log files, and can be used with the new target property system to create detailed, customizable server logs.

**Comment by jonqrandom** [comment]
sorry i haven't seen this sooner - that looks _amazing_, thank you! i checked r/feedthebeast and you don't seem to have posted a link to this, would you like to/would it be ok if i did? i think a lot of people there would appreciate it too! :)  
EDIT: when your new update is on curseforge, anyways - sorry, i kinda jumped the gun there! :blush:

**Comment by coolsquid** [comment]
I have added the following "target properties":

**Mobs:**
- `name` (e.g. `Wolf`, `custom name`, or `username`)
- `uuid` (e.g. `1b284948-a0e9-4f53-9ecd-dc2d9470934f`)
- `type` (e.g. `minecraft:zombie`)
- `position` (e.g. `[x=-522,y=69,z=418]`)
- `x_position` (e.g. `-522`)
- `y_position` (e.g. `69`)
- `z_position` (e.g. `418`)

**Players:**
- `ip` (e.g. `12.34.56.78` in multiplayer, or `local` in singleplayer)
- All target properties for mobs.

**Blocks:**
- `id` (e.g. `minecraft:stone`)
- `position` (e.g. `[x=-522,y=69,z=418]`)
- `x_position` (e.g. `-522`)
- `y_position` (e.g. `69`)
- `z_position` (e.g. `418`)

**Miscellaneous:**
- `damage_source.name`
- `damage_amount`
- `message` (chat-related events)
- `hand`
- `command`
- `command_arguments.list`

Should anything else be added?
>i checked r/feedthebeast and you don't seem to have posted a link to this, would you like to/would it be ok if i did?

I did mention it in my [1.12 update post](https://www.reddit.com/r/feedthebeast/comments/6oiqwb/react_toxicrain_screenshotuploader_and_logfilters/). Feel free to post it again, though.

**Comment by jonqrandom** [comment]
that's wonderful, that really is!
> Should anything else be added?

this is my fault, i should've remembered it when i first made the issue; uuid probably wants to be available as uuid_most and uuid_least too, as that's how they're stored in nbt tags, and minecraft commands don't have any way of natively using the uuid as it's commonly expressed :/  
  
the current HP and maybe armour for mobs would likely be very handy. 

if you feel like it, you _could_ (is "recursively" the right word here?) add the mob/block target properties of whatever the mob in question is targeting.    
so potentially a script could use %%%mob.target.position%%% to occasionally set fires or place particles where a mob is looking. or maybe even %%%mob.target.target.position%%% - i can see that one being useful in .mcfunction scripts, f'rinstance, so checking if %%%mob.uuid%%% == %%%mob.target.target.uuid%%% would let you figure out if two entities are mutually targeting each other. in combination with e.g. fake players, being able to "daisy-chain" targeting could be powerful.  
i appreciate this could be _way_ out of scope, so please take this last one as just me thinking out loud?
  
> I did mention it in my 1.12 update post. Feel free to post it again, though.

i think this update is worth mentioning, i reckon a lot of packmakers will absolutely love the functionality you're including! thank you again! =)

**Comment by coolsquid** [comment]
I will be releasing the next version later today.
>the current HP and maybe armour for mobs would likely be very handy.

Added.
>this is my fault, i should've remembered it when i first made the issue; uuid probably wants to be available as uuid_most and uuid_least too, as that's how they're stored in nbt tags, and minecraft commands don't have any way of natively using the uuid as it's commonly expressed :/

Are you sure? I seem to be able to use /kill with my UUID...
>if you feel like it, you could (is "recursively" the right word here?) add the mob/block target properties of whatever the mob in question is targeting.

That would require too much work, I'm afraid. Maybe later.

**Comment by jonqrandom** [comment]
> Are you sure? I seem to be able to use /kill with my UUID...

oh, sweet, then i'm totally wrong! the wiki gave me the opposite impression but it's all good =)
> That would require too much work, I'm afraid. Maybe later.

no, i totally understand, that really was an "as long as i'm dreaming" kinda thing! seriously, thank you ever so much again, the extra scope you've just given me and other packmakers (those of us who can't code anyway) is amazing! <3

**Comment by coolsquid** [comment]
Version [1.1.0](https://github.com/coolsquid/React/releases/tag/v1.1.0) has been released on GitHub, and will be uploaded to CurseForge as soon as I've finished the changelog.
