### ISSUE TITLE
Soft Crash on Server Join?

### ISSUE THREAD

**Issue by carstorm** [coolsquid/React#2]
SP works fine, and the dedicated server works fine, however when a client tries to join a server they get immediately disconnected with the following in the client log files (the server shows nothing abnormal): https://pastebin.com/H12NWgqk

**Comment by coolsquid** [comment]
Try [v1.1.1](https://github.com/coolsquid/React/releases/tag/v1.1.1).

**Comment by carstorm** [comment]
When will v1.1.1 be on Curse?

**Comment by coolsquid** [comment]
I will upload it as soon as you've confirmed that it solves the issue.

**Comment by coolsquid** [comment]
I will upload it to Curse when you confirm that it solves the issue.

**Comment by carstorm** [comment]
Sorry I missed this notification. It solves the issue.
