### ISSUE TITLE
Suggestion: Spawn action

### ISSUE THREAD

**Issue by Matryoshika** [coolsquid/React#3]
Would it be possible to add an action for spawning entities, both normal entities, as well as itemstacks?
This would open up a whole new world of possibilities for React, allowing everything from scripted battles, like arena-style gladiatorial fights, to adding specific loot-drops to blocks, depending on specific items used, including non-tool ones.

**Comment by coolsquid** [comment]
Version 1.2.0 is live, with support for the spawn_mob and spawn_item actions.

Example usage:

    server_chat=[
        # Spawns a sheep five blocks above any player who sends a chat message that contains the word "sheep".
    	{
    		action=spawn_mob
    		target=player // The location of the new mob will be based on the target's location.
    		parameters {
    			mob_type="minecraft:sheep"
    			y=~5 // Changes the y-coord relative to the target's location.
    		}
    		conditions {
    			message=".*sheep.*"
    		}
    	}
        # Spawns a diamond five blocks above any player who sends a chat message that contains the word "diamond".
    	{
    		action=spawn_item
    		target=player
    		parameters {
    			item="minecraft:diamond"
    			y=~5
    			nbt {
    				key="value"
    			}
    		}
    		conditions {
    			message=".*diamond.*"
    		}
    	}
    ]
