### ISSUE TITLE
[Crash] Server crash on lastest version

### ISSUE THREAD

**Issue by armuell** [coolsquid/React#4]
Java version: 1.8.0.161
Forge Version: forge-1.12.2-14.23.2.2613-universal

Crash report: 
http://stackless.io/pom/crash-2018-03-18_11.14.33-server.txt

**Comment by coolsquid** [comment]
This has (hopefully) been fixed in [v1.2.1](https://github.com/coolsquid/React/releases/tag/v1.2.1). If the problem persists, please reopen this issue.

Thanks for the report.
