### ISSUE TITLE
Exact time for the world time target filter

### ISSUE THREAD

**Issue by lobbienjonsji** [coolsquid/React#5]
Right now, when the target filter "time" for worlds is selected, and set to a specific time in ticks (eg. 18000 for midnight or 6000 for noon), no world is getting selected. I would love to have the possibility to chose an exact time to make an action happen exactly once a day.

**Comment by coolsquid** [comment]
The "time" filter currently only takes "day" and "night" as values. I'll add the ability to specify the time in ticks as well.

**Comment by coolsquid** [comment]
Done. A new version will be released shortly. A specific time can be specified in the "time" filter (e.g. "time = 6000"), or a range can be specified using the "min_time" and "max_time" filters.
