### ISSUE TITLE
set_block

### ISSUE THREAD

**Issue by mobeonsa** [coolsquid/React#7]
What is the right syntax of "action=set_block" coordinates? Then i tried x = 1, it works but ~ or ~1  or "~" doesn't work. Log says:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number:

Full script: 
```
block_place=[
	{
		action=cancel
		conditions {
			block  {
				name="minecraft:anvil"
			}
		}
	}
	{
		action=set_block
		parameters {
			block="minecraft:anvil"
			x=~0
			y=~0
			z=~0
		}
	}
]
```
PS I'm trying to make anvil falling doesn't break it.
PS PS Sorry for bad eng(

**Comment by coolsquid** [comment]
If the coordinate contains "~", it must be surrounded by quotation marks.

```
block_place=[ # is this supposed to be "block_break"?
	{
		action=cancel
		conditions {
			block  {
				name="minecraft:anvil"
			}
		}
	}
	{
		action=set_block
		parameters {
			block="minecraft:anvil"
			x="~0"
			y="~0"
			z="~0"
		}
	}
]
```
